spring:
  application:
    name: ProducteService

server:
  port: 5000

resilience4j:
  circuitbreaker:
    instances:
      productApiClientCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.RestClientException
  retry:
    instances:
      productApiClientRetry:
        max-attempts: 2
        wait-duration:
          seconds: 1
        retry-exceptions:
          - org.springframework.web.client.RestClientException

api-client:
  product-url: http://localhost:3001/product