spring:
  application:
    name: ProducteService

server:
  port: 5000

resilience4j:
  circuitbreaker:
    instances:
      productApiClientCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        record-exceptions:
          - java.lang.Exception
  timelimiter:
    instances:
      productApiClientTimeLimiter:
              cancelRunningFuture: true
              timeoutDuration: 6s

api-client:
  product-url: http://localhost:3001/product

logging:
  level:
    root: info
    test.amssoluctions.productservice: off